/**
 * JSX Export System
 *
 * Centralized export logic for SceneForge.
 * Generates deterministic, human-readable React Three Fiber JSX.
 *
 * Export Modes:
 * - sceneOnly: Just the meshes, no lights or canvas
 * - withLights: Meshes + ambient/directional lights
 * - withCanvas: Full canvas wrapper with controls
 *
 * Design Principles:
 * - Deterministic output (same input → same output)
 * - Human-readable code
 * - No runtime dependencies in scene-only export
 * - Stable property ordering
 */

import type { SceneObject, MeshObject } from '@/store/scene-store'

// ============================================================================
// EXPORT OPTIONS
// ============================================================================

export type ExportMode = 'sceneOnly' | 'withLights' | 'withCanvas'

export interface ExportOptions {
  mode: ExportMode
}

// ============================================================================
// FORMATTING UTILITIES
// ============================================================================

/** Format number for clean output (remove unnecessary decimals) */
function formatNum(n: number): string {
  const rounded = Math.round(n * 1000) / 1000
  return rounded === Math.floor(rounded)
    ? rounded.toString()
    : rounded.toFixed(3).replace(/\.?0+$/, '')
}

/** Format Vector3 tuple as JSX array */
function formatVector(v: [number, number, number]): string {
  return `[${v.map(formatNum).join(', ')}]`
}

// ============================================================================
// GEOMETRY GENERATION
// ============================================================================

/** Get geometry JSX for mesh type */
function getGeometry(type: string): string {
  switch (type) {
    case 'box': return '<boxGeometry />'
    case 'sphere': return '<sphereGeometry args={[1, 32, 32]} />'
    case 'cylinder': return '<cylinderGeometry args={[1, 1, 2, 32]} />'
    default: return '<boxGeometry />'
  }
}

// ============================================================================
// OBJECT GENERATION
// ============================================================================

/** Generate JSX for a single mesh object */
function generateMesh(obj: MeshObject, indent: string): string {
  const lines = [
    `${indent}<mesh`,
    `${indent}  position={${formatVector(obj.position)}}`,
    `${indent}  rotation={${formatVector(obj.rotation)}}`,
    `${indent}  scale={${formatVector(obj.scale)}}`,
    `${indent}>`,
    `${indent}  ${getGeometry(obj.type)}`,
    `${indent}  <meshStandardMaterial color="${obj.material.color}" />`,
    `${indent}</mesh>`,
  ]
  return lines.join('\n')
}

/** Generate JSX for any scene object */
function generateObject(obj: SceneObject, indent: string): string {
  return generateMesh(obj, indent)
}

// ============================================================================
// MAIN EXPORT FUNCTION
// ============================================================================

/** Generate complete JSX code from scene objects */
export function generateJSX(
  objects: SceneObject[],
  options: ExportOptions = { mode: 'sceneOnly' }
): string {
  const { mode } = options

  // Determine indent based on mode (canvas wrapper adds nesting)
  const objectIndent = mode === 'withCanvas' ? '        ' : '      '

  // Generate object JSX
  const objectsJSX = objects.length > 0
    ? objects.map(obj => generateObject(obj, objectIndent)).join('\n')
    : `${objectIndent}{/* No objects in scene */}`

  // Build output based on mode
  switch (mode) {
    case 'sceneOnly':
      return generateSceneOnly(objectsJSX)
    case 'withLights':
      return generateWithLights(objectsJSX)
    case 'withCanvas':
      return generateWithCanvas(objectsJSX)
    default:
      return generateSceneOnly(objectsJSX)
  }
}

// ============================================================================
// MODE-SPECIFIC GENERATORS
// ============================================================================

/** Scene Only - Just objects, no lights or canvas */
function generateSceneOnly(objects: string): string {
  return `/**
 * Scene Component
 * Generated by SceneForge
 *
 * Usage: Import into your React Three Fiber Canvas.
 * Add your own lighting as needed.
 */

export function Scene() {
  return (
    <>
${objects}
    </>
  )
}
`
}

/** With Lights - Objects + standard lighting setup */
function generateWithLights(objects: string): string {
  return `/**
 * Scene Component
 * Generated by SceneForge
 *
 * Usage: Import into your React Three Fiber Canvas.
 * Includes standard lighting setup.
 */

export function Scene() {
  return (
    <>
      {/* Lighting */}
      <ambientLight intensity={0.4} />
      <directionalLight position={[10, 10, 5]} intensity={0.8} />

      {/* Scene Objects */}
${objects}
    </>
  )
}
`
}

/** With Canvas - Full wrapper with Canvas, lights, and controls */
function generateWithCanvas(objects: string): string {
  return `/**
 * SceneCanvas Component
 * Generated by SceneForge
 *
 * Usage: Drop this component directly into your React app.
 * The Canvas fills its parent container - wrap in a sized div:
 *   <div style={{ width: '100%', height: '400px' }}>
 *     <SceneCanvas />
 *   </div>
 *
 * Includes Canvas, lighting, and camera controls.
 */

import { Canvas } from '@react-three/fiber'
import { OrbitControls } from '@react-three/drei'

export function SceneCanvas() {
  return (
    <Canvas camera={{ position: [5, 5, 5], fov: 50 }}>
      {/* Lighting */}
      <ambientLight intensity={0.4} />
      <directionalLight position={[10, 10, 5]} intensity={0.8} />

      {/* Camera Controls */}
      <OrbitControls />

      {/* Scene Objects */}
${objects}
    </Canvas>
  )
}
`
}
