/**
 * CodePanel Component
 * 
 * Live JSX code preview panel.
 * Generates React Three Fiber JSX from Zustand scene state.
 * 
 * Export Flow:
 * Zustand Scene State → JSX Serializer → Code String
 * 
 * Key Requirements:
 * - Deterministic output (same state → same code)
 * - Human-readable JSX
 * - No random IDs in output
 * - No loops or dynamic runtime logic in exported JSX
 */

'use client'

import { useState, useMemo } from 'react'
import { useSceneStore } from '@/store/scene-store'
import type { SceneObject } from '@/store/scene-store'

export function CodePanel() {
  const objects = useSceneStore((state) => state.objects)
  const [copied, setCopied] = useState(false)

  // Generate JSX code deterministically from scene state
  const code = useMemo(() => generateJSX(objects), [objects])

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  return (
    <section className="h-48 bg-[#242424] border-t border-[#3d3d3d] flex flex-col">
      {/* Header */}
      <div className="h-8 px-3 flex items-center justify-between border-b border-[#3d3d3d]">
        <span className="text-xs font-medium text-[#a3a3a3] uppercase tracking-wide">
          Live JSX Export
        </span>
        <div className="flex items-center gap-2">
          <span className="text-xs text-[#737373]">Scene.tsx</span>
          <button
            onClick={handleCopy}
            className={`px-2 py-1 text-xs rounded transition-colors ${
              copied
                ? 'bg-green-600/20 text-green-400'
                : 'bg-[#2d2d2d] hover:bg-[#363636] text-[#a3a3a3]'
            }`}
          >
            {copied ? '✓ Copied!' : 'Copy Code'}
          </button>
        </div>
      </div>

      {/* Code Area */}
      <div className="flex-1 overflow-auto p-2">
        <pre className="text-xs font-mono text-[#a3a3a3] whitespace-pre">
          <code>{code}</code>
        </pre>
      </div>
    </section>
  )
}

/**
 * JSX Code Generator
 * 
 * Serializes scene objects to clean React Three Fiber JSX.
 * Output is deterministic - same input always produces same output.
 */
function generateJSX(objects: SceneObject[]): string {
  // Format a number for output (remove unnecessary decimals)
  const formatNum = (n: number): string => {
    const rounded = Math.round(n * 1000) / 1000
    return rounded === Math.floor(rounded) ? rounded.toString() : rounded.toFixed(3).replace(/\.?0+$/, '')
  }

  // Format a Vector3 tuple
  const formatVector = (v: [number, number, number]): string => {
    return `[${v.map(formatNum).join(', ')}]`
  }

  // Generate geometry component based on object type
  const getGeometry = (type: string): string => {
    switch (type) {
      case 'box': return '<boxGeometry />'
      case 'sphere': return '<sphereGeometry args={[1, 32, 32]} />'
      case 'cylinder': return '<cylinderGeometry args={[1, 1, 2, 32]} />'
      default: return '<boxGeometry />'
    }
  }

  // Generate mesh JSX for a single object
  const generateMesh = (obj: SceneObject, indent: string): string => {
    const lines = [
      `${indent}<mesh`,
      `${indent}  position={${formatVector(obj.position)}}`,
      `${indent}  rotation={${formatVector(obj.rotation)}}`,
      `${indent}  scale={${formatVector(obj.scale)}}`,
      `${indent}>`,
      `${indent}  ${getGeometry(obj.type)}`,
      `${indent}  <meshStandardMaterial color="${obj.material.color}" />`,
      `${indent}</mesh>`,
    ]
    return lines.join('\n')
  }

  // Generate complete component
  const meshes = objects.length > 0
    ? objects.map(obj => generateMesh(obj, '      ')).join('\n')
    : '      {/* No objects in scene */}'

  return `/**
 * Scene Component
 * Generated by SceneForge
 * 
 * Usage: Import this component into your React Three Fiber Canvas.
 */

export function Scene() {
  return (
    <>
${meshes}
    </>
  )
}
`
}

